name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    pull_request:
      - ready_for_review
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: statikbe/.github/.github/workflows/craftcms/ci.yml@main
    with:
      craft_version: '4'
      jobs: '["ecs", "phpstan"]'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
